site_name: 'Мой персональный сайт'
site_description: 'Персональный сайт-визитка'
site_author: 'Ольга Девятилова'
site_url: 'https://helga1206.github.io/devops-lab-deviatilova/'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - header.autohide
  palette:
    - scheme: default
      primary: deep purple
      accent: pink
      toggle:
        icon: material/weather-night
        name: Включить тёмную тему
    - scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Включить светлую тему
  logo: logo.png
  language: ru

nav:
  - 'Главная': index.md
  - 'О себе': about.md
  - 'Проекты': projects.md
  - 'Контакты': contacts.md
  - 'Резюме': resume.md
  - 'Достижения': achivments.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/helga1206/devops-lab-deviatilova.git

copyright: Copyright &copy; 2024 - 2025 Olga Deviatilova



